app/models/applications.py
from datetime import datetime

from .. import db
from flask_moment import Moment


class Application(db.Model):
    __tablename__ = 'applications'
    id = db.Column(db.Integer, primary_key=True)
    job_listing_id = db.Column(db.Integer, db.ForeignKey('job_listings.id'))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    complete_profile = db.Column(db.Boolean(), index=True, default=False)
    agreement = db.Column(db.Boolean(), index=True, default=False)
    status = db.Column(db.String(120), default='pending')
    education_documents = db.relationship('EducationDocuments', backref='applications', lazy='dynamic')
    days = db.relationship('DaysAvailable', backref='applications', lazy='dynamic')
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return '<Application\'%s\'>' % self.job_listing_id

    def get_time(self):
        return self.createdAt

app/models/employment_history.py
from datetime import datetime

from .. import db


class EmploymentHistory(db.Model):
    __tablename__ = 'employment_history'
    id = db.Column(db.Integer, primary_key=True)
    name_of_institution = db.Column(db.String(64), index=True)
    year_from = db.Column(db.String(64), index=True)
    year_to = db.Column(db.String(64))
    duration = db.Column(db.String(64), index=True)
    job_group = db.Column(db.String(64), index=True)
    designation = db.Column(db.String(64))
    gross_salary = db.Column(db.String(64))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'), index=True)
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return '<EmploymentHistory \'%s\'>' % self.id


class Employment(db.Model):
    __tablename__ = 'employment'
    id = db.Column(db.Integer, primary_key=True)
    if_not_employed = db.Column(db.Boolean, default=False)
    ministry = db.Column(db.String(64), index=True)
    station = db.Column(db.String(64), index=True)
    pf_number = db.Column(db.String(64))
    personal_employment_no = db.Column(db.String(64), index=True)
    present_substantive_post = db.Column(db.String(64), index=True)
    job_group = db.Column(db.String(64), index=True)
    date_of_current_appointment = db.Column(db.DateTime())
    effective_date = db.Column(db.DateTime())
    position_held = db.Column(db.String(64))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'), index=True)
    terms_of_service = db.Column(db.String(64), index=True)
    if_other = db.Column(db.String(200))
    gross_salary = db.Column(db.String(64))
    current_employer = db.Column(db.String(64))

    def __repr__(self):
        return '<Employment \'%s\'>' % self.id

app/models/publisher.py
from .. import db
from datetime import datetime
from flask import current_app
from app.models.roles import Role


class Publisher(db.Model):
    __tablename__ = "publishers"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    user_id = db.Column(db.Integer(), db.ForeignKey("users.id"))
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(
        db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow
    )
    phones = db.relationship(
        "Pubphones", backref="profile", lazy="dynamic", cascade="all,delete-orphan"
    )
    emails = db.relationship(
        "Pubemails", backref="profile", lazy="dynamic", cascade="all,delete-orphan"
    )
    locations = db.relationship(
        "Publocations", backref="profile", lazy="dynamic", cascade="all,delete-orphan"
    )

    def getLocations(self):
        data = self.locations.group_by(Publocations.country)
        return data


class Pubphones(db.Model):
    __tablename__ = "pubphones"
    id = db.Column(db.Integer, primary_key=True)
    phone_number = db.Column(db.String(120))
    publisher_id = db.Column(db.Integer(), db.ForeignKey("publishers.id"))


class Pubemails(db.Model):
    __tablename__ = "pubemails"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120))
    publisher_id = db.Column(db.Integer(), db.ForeignKey("publishers.id"))


class Publocations(db.Model):
    __tablename__ = "Publocations"
    id = db.Column(db.Integer, primary_key=True)
    city = db.Column(db.String(120))
    country = db.Column(db.String(120))
    publisher_id = db.Column(db.Integer(), db.ForeignKey("publishers.id"))

    def get_count(self):
        return (
            Publocations.query.filter_by(publisher_id=self.publisher_id)
            .group_by(Publocations.publisher_id)
            .count()
        )

app/api/views.py
import uuid

from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    flash,
    send_from_directory)
from flask_ckeditor import upload_success, upload_fail
from flask_login import current_user, login_required, login_user
import PIL, simplejson, traceback
from PIL import Image
from flask_rq import get_queue
from flask_uploads import patch_request_class

from app.models.job_listings import *
from app.models.applications import *
from app.models.education_documents import *
from app.models.users import *
from app.api.forms import *
from app.auth.forms import *
from app import db
from app.email import send_email
from app.models import *
from app.auth.email import send_password_reset_email
from app.auth.admin_decorators import check_confirmed
from app.decorators import checks_required
from werkzeug.utils import secure_filename
from app.lib.upload_file import uploadfile
from app.auth.email import send_applicant_submitted

publisher = Blueprint("publisher", __name__)


@publisher.route("/")
@login_required
@check_confirmed
def dashboard():
    app_count = ManualEntry.query.filter_by(data_entered_by=current_user.id).count()
    manual_applications = ManualEntry.query.filter_by(data_entered_by=current_user.id) \
        .order_by(ManualEntry.createdAt.desc()).all()
    return render_template("publishers/dashboard.html", app_count=app_count, manual_applications=manual_applications)


@publisher.route("/applications")
@login_required
@check_confirmed
def applications():
    manual_applications = ManualEntry.query.order_by(ManualEntry.createdAt.desc()).all()
    return render_template("publishers/applications.html", manual_applications=manual_applications)


@publisher.route("/add_application", methods=("GET", "POST"))
@login_required
@check_confirmed
def add_applicant():
    form = DataEntryForm()
    form.job_title.choices = [(row.id, row.job_title) for row in Listing.query.all()]
    if form.validate_on_submit():
        listing = Listing.query.filter_by(id=form.job_title.data).first_or_404()
        manual_user = User(
            first_name=form.first_name.data,
            second_name=form.second_name.data,
            surname=form.surname.data,
            gender=form.gender.data,
            id_number=form.id_number.data,
            email=form.email.data,
            phone_number_personal=form.phone_number_personal.data,
            address=form.address.data,
            country_of_residence=form.country_of_residence.data,
            home_county=form.home_county.data,
            ethnicity=form.ethnicity.data,
            phone_number_alternate=form.phone_number_alternate.data,
            civil_status=form.civil_status.data,
            nationality=form.nationality.data,
            disability=form.disability.data,
            disability_nature=form.disability_nature.data,
            disability_registration_details=form.disability_registration_details.data,
            highest_level_education=form.highest_level_education.data,
            role_id='2'
        )
        me = ManualEntry(
            job_title=listing.job_title,
            job_reference_number=listing.job_reference_number,
            job_listing_id=listing.id,
            title=form.title.data,
            first_name=form.first_name.data,
            second_name=form.second_name.data,
            surname=form.surname.data,
            gender=form.gender.data,
            id_number=form.id_number.data,
            email=form.email.data,
            phone_number_personal=form.phone_number_personal.data,
            address=form.address.data,
            age=form.age.data,
            country_of_residence=form.country_of_residence.data,
            home_county=form.home_county.data,
            ethnicity=form.ethnicity.data,
            phone_number_alternate=form.phone_number_alternate.data,
            civil_status=form.civil_status.data,
            nationality=form.nationality.data,
            disability=form.disability.data,
            disability_nature=form.disability_nature.data,
            disability_registration_details=form.disability_registration_details.data,
            highest_level_education=form.highest_level_education.data,
            phd_certificate_obtained=form.phd_certificate_obtained.data,
            masters_certificate_obtained=form.masters_certificate_obtained.data,
            degree_certificate_obtained=form.degree_certificate_obtained.data,
            diploma_certificate_obtained=form.diploma_certificate_obtained.data,
            higher_diploma_certificate_obtained=form.higher_diploma_certificate_obtained.data,
            certificate_obtained=form.certificate_obtained.data,
            relevant_certification=form.relevant_certification.data,
            registration=form.registration.data,
            total_work_experience=form.total_work_experience.data,
            relevant_work_experience=form.relevant_work_experience.data,
            mode_of_application=form.mode_of_application.data,
            data_entered_by=current_user.id,
            cv=form.cv.data,
            cover_letter=form.cover_letter.data,
            application_form=form.application_form.data
        )
        db.session.add(manual_user)
        db.session.add(me)
        db.session.commit()
        flash("Manual Application Submitted Successfully.", "success")
        return redirect(url_for("publisher.employment_history_by_details", user_id=manual_user.id))
    return render_template("publishers/add_applicant.html", form=form)


@publisher.route("/_employment_history/<user_id>", methods=["post", "get"])
@login_required
@check_confirmed
def employment_history_by_details(user_id):
    user = User.query.filter_by(id=user_id).first()
    form = EmpForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.commit()
        flash("Employment History updated successfully.", "success")
        return redirect(url_for("publisher.dashboard"))
    return render_template("publishers/_employment_history.html", form=form, user=user)


@publisher.route("/_get_model")
def _get_model():
    job_title = request.args.get("job_title", 0, type=str)
    listing = Listing.query.filter_by(job_title=job_title).first_or_404()
    job_reference = listing.job_reference_number
    return jsonify(job_reference)


@publisher.route("/edit_application/<id>", methods=("GET", "POST"))
@login_required
@check_confirmed
def edit_application(id):
    app = ManualEntry.query.filter_by(id=id).first_or_404()
    form = EditDataEntryForm(obj=app)
    form.job_title.choices = [(row.job_title, row.job_title) for row in Listing.query.all()]
    if form.validate_on_submit():
        form.populate_obj(app)
        manual_user = User(
            first_name=form.first_name.data,
            second_name=form.second_name.data,
            surname=form.surname.data,
            gender=form.gender.data,
            id_number=form.id_number.data,
            email=form.email.data,
            phone_number_personal=form.phone_number_personal.data,
            address=form.address.data,
            country_of_residence=form.country_of_residence.data,
            home_county=form.home_county.data,
            ethnicity=form.ethnicity.data,
            phone_number_alternate=form.phone_number_alternate.data,
            civil_status=form.civil_status.data,
            nationality=form.nationality.data,
            disability=form.disability.data,
            disability_nature=form.disability_nature.data,
            disability_registration_details=form.disability_registration_details.data,
            highest_level_education=form.highest_level_education.data,
            role_id='2'
        )

        db.session.add(manual_user)
        db.session.commit()
        flash("Manual Application Edited Successfully.", "success")
        return redirect(url_for("publisher.employment_history_by_details", user_id=manual_user.id))
    return render_template('publishers/edit_application.html', form=form, app=app)

app/templates/publishers/applications.html
{% extends 'layouts/data_base.html' %}

{% block custom_head_tags %}
    {{ super() }}
    <!-- CORE CSS-->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ url_for('static', filename='vendors/prismjs/themes/prism.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons/buttons.dataTables.min.css') }}">
    <!-- end plugin css for this page -->
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <nav class="page-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('publisher.applications') }}">Applications</a></li>
                <li class="breadcrumb-item active" aria-current="page">VIEW APPLICATIONS</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 col-xl-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-baseline mb-2">
                        <h6 class="card-title mb-0">Manual Applications</h6>
                        <div class="dropdown mb-2">
                            <button class="btn p-0" type="button" id="dropdownMenuButton7" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton7">
                                <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="eye"
                                                                                               class="icon-sm mr-2"></i>
                                    <span class="">View</span></a>
                                <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="edit-2"
                                                                                               class="icon-sm mr-2"></i>
                                    <span class="">Edit</span></a>
                                <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="trash"
                                                                                               class="icon-sm mr-2"></i>
                                    <span class="">Delete</span></a>
                                <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="printer"
                                                                                               class="icon-sm mr-2"></i>
                                    <span class="">Print</span></a>
                                <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="download"
                                                                                               class="icon-sm mr-2"></i>
                                    <span class="">Download</span></a>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0">Applicant Name</th>
                                <th class="pt-0">Job Ref. No.</th>
                                <th class="pt-0">Job Title</th>
                                <th class="pt-0">Application Date</th>
                                <th class="pt-0">Gender</th>
                                <th class="pt-0">ID Number</th>
                                <th class="pt-0">Home County</th>
                                <th class="pt-0">Ethnicity</th>
                                <th class="pt-0">Nationality</th>
                                <th class="pt-0">Date of Birth</th>
                                <th class="pt-0">Phone Number</th>
                                <th class="pt-0">Email</th>
                                <th class="pt-0">Address</th>
                                <th class="pt-0">Alternative Contact</th>
                                <th class="pt-0">Disability</th>
                                <th class="pt-0">Disability Details</th>
                                <th class="pt-0">Highest Level Of Education</th>
                                <th class="pt-0">Education Details</th>
                                <th class="pt-0">Relevant Course or Certification</th>
                                <th class="pt-0">Registration to Professional Bodies</th>
                                <th class="pt-0">Summary</th>
                                <th class="pt-0">Total Work Experience</th>
                                <th class="pt-0">Relevant Work Experience</th>
                                <th class="pt-0">Status</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for application in manual_applications %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>
                                        <a href="#">
                                            {{ application.first_name }} {{ application.surname }}</a>
                                    </td>
                                    <td><a href="#">{{ application.job_reference_number }}</a>
                                    </td>
                                    <td><a href="#">{{ application.job_title }}</a>
                                    </td>
                                    <td>
                                        {{ moment(application.get_time()).format('MMMM Do YYYY, h:mm:ss a') }}
                                    </td>
                                    <td>{{ application.gender }}</td>
                                    <td>{{ application.id_number }}</td>
                                    <td>{{ application.home_county }}</td>
                                    <td>{{ application.ethnicity }}</td>
                                    <td>{{ application.nationality }}</td>
                                    <td>{{ application.age }}</td>
                                    <td>{{ application.phone_number_personal }}</td>
                                    <td>{{ application.email }}</td>
                                    <td>{{ application.address }}</td>
                                    <td>{{ application.phone_number_alternate }}</td>
                                    <td>{% if application.disability %}{{ application.disability }}{% else %}
                                        None{% endif %}</td>
                                    <td>{% if application.disability_nature %}
                                        {{ application.disability_nature }}{% else %}None{% endif %}</td>
                                    <td>{{ application.highest_level_education }}</td>
                                    <td>
                                        <ul style="list-style: none;padding-bottom: 0;margin-bottom: 0;">
                                            <li>{{ application.phd_certificate_obtained }}</li>
                                            <li>{{ application.masters_certificate_obtained }}</li>
                                            <li>{{ application.degree_certificate_obtained }}</li>
                                            <li>{{ application.higher_diploma_certificate_obtained }}</li>
                                            <li>{{ application.diploma_certificate_obtained }}</li>
                                            <li>{{ application.certificate_obtained }}</li>
                                        </ul>
                                    </td>
                                    <td>{{ application.relevant_certification }}</td>
                                    <td>{{ application.registration }}</td>
                                    <td></td>
                                    <td>{{ application.total_work_experience }}</td>
                                    <td>{{ application.relevant_work_experience }}</td>
                                    <td><span class="badge badge-success">Submitted</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    <!-- plugin js for this page -->
    <script src="{{ url_for('static', filename='vendors/prismjs/prism.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/clipboard/clipboard.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/datatables.net/jquery.dataTables.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ url_for('static', filename='js/buttons/dataTables.buttons.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jszip.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/pdfmake.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vfs_fonts.js') }}"></script>
    <script src="{{ url_for('static', filename='js/buttons/buttons.html5.min.js') }}"></script>
    <!-- end plugin js for this page -->

    <script>

        $(function () {
            'use strict';

            $(function () {
                $('#dataTable').DataTable({
                    "aLengthMenu": [
                        [10, 30, 50, -1],
                        [10, 30, 50, "All"]
                    ],
                    "iDisplayLength": 10,
                    "language": {
                        search: ""
                    },
                    dom: 'Bfrtip',
                    buttons: [
                        'copyHtml5',
                        'csvHtml5',
                        'pdfHtml5',
                        {
                            extend: 'excel',
                            messageTop: 'All The Applications.'
                        },
                    ]
                });
                $('#dataTable').each(function () {
                    var datatable = $(this);
                    // SEARCH - Add the placeholder for Search and Turn this into in-line form control
                    var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
                    search_input.attr('placeholder', 'Search');
                    search_input.removeClass('form-control-sm');
                    // LENGTH - Inline-Form control
                    var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
                    length_sel.removeClass('form-control-sm');
                });
            });

        });
    </script>
    <script>
        $(function () {
            'use strict';

            if ($('#datePickerExample').length) {
                var date = new Date();
                var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
                $('#datePickerExample').datepicker({
                    format: "dd/mm/yyyy",
                    todayHighlight: true,
                    autoclose: true
                });
                // var ub = new Date('{{user_dob}}');
                $('#datePickerExample').datepicker('setDate', today)
            }
        });
    </script>
{% endblock %}

app/templates/publishers/login.html
{% extends 'home/home_base.html' %}

{% block home_content %}
<div class="page-content d-flex align-items-center justify-content-center">
    <div class="row w-100 mx-0 auth-page">
        <div class="col-md-12 col-xl-12 mx-auto" style="padding-top: 44px;text-align: center;">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="logo">
        </div>
    </div>
</div>
<div class="page-content d-flex align-items-center justify-content-center pt-0">
    <div class="row w-100 mx-0 auth-page">
        <div class="col-md-12 col-xl-12 mx-auto">
            <div class="card">
                <div class="row">
                    <div class="col-md-8">
                        {% with messages = get_flashed_messages(with_categories=True) %}
                        {% if messages %}
                        {% for category, msg in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            <strong>!</strong> {{ msg }}.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% endwith %}
                        <div class="auth-form-wrapper px-4 py-5 col-md-10">
                            <a href="#" class="noble-ui-logo d-block mb-2">KUTRRH.<span>Careers</span></a>
                            <h5 class="text-muted font-weight-normal mb-4">Welcome back! Log in to your
                                account.</h5>
                            <form action="" class="f-login-form" method="POST">
                                {{loginform.hidden_tag()}}
                                <div class="form-group">
                                    <label for="" class="">Email address </label>
                                    {{loginform.email(class="form-control", placeholder="Email")}}
                                    {%for error in loginform.email.errors%}
                                    <span class="text-danger">{{error}}</span>
                                    {%endfor%}
                                </div>
                                <div class="form-group">
                                    <label for="" class="">Password </label>
                                    {{loginform.password(class="form-control", autocomplete="current-password",
                                    placeholder="Password")}}
                                    {%for error in loginform.password.errors%}
                                    <span class="text-danger">{{error}}</span>
                                    {%endfor%}
                                </div>
                                <div class="form-check form-check-flat form-check-primary">
                                    <label class="form-check-label">
                                        <input type="checkbox" class="form-check-input">
                                        {{loginform.remember_me(class="form-control remember_me", placeholder="Email")}}
                                        Remember me
                                    </label>
                                    {%for error in loginform.remember_me.errors%}
                                    <span class="text-danger">{{error}}</span>
                                    {%endfor%}
                                </div>
                                <div class="mt-3">
                                    {{loginform.submit1(class="btn btn-primary mr-2 mb-2 mb-md-0 text-white")}}
                                </div>

                                <a href="{{url_for('account.reset_password_request')}}" class="d-block mt-3 text-muted">Forgot
                                    password?</a>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock home_content %}

{% block footer %}{% endblock footer %}